// Auto generated file
// Patch: 0.10.0
// Build: 5195

Public Enum EObjectFields
{
    OBJECT_FIELD_GUID = 0x0,                                                      // 0x000 - Size: 2 - Type: GUID - Flags: PUBLIC
    OBJECT_FIELD_TYPE = 0x2,                                                      // 0x002 - Size: 1 - Type: INT - Flags: PUBLIC
    OBJECT_FIELD_ENTRY = 0x3,                                                     // 0x003 - Size: 1 - Type: INT - Flags: PUBLIC
    OBJECT_FIELD_SCALE_X = 0x4,                                                   // 0x004 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    OBJECT_FIELD_PADDING = 0x5,                                                   // 0x005 - Size: 1 - Type: INT - Flags: NONE
    OBJECT_END = 0x6                                                              
}
Public Enum EItemFields
{
    ITEM_FIELD_OWNER = EObjectFields.OBJECT_END + 0x0,                            // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    ITEM_FIELD_CONTAINED = EObjectFields.OBJECT_END + 0x2,                        // 0x008 - Size: 2 - Type: GUID - Flags: PUBLIC
    ITEM_FIELD_CREATOR = EObjectFields.OBJECT_END + 0x4,                          // 0x00A - Size: 2 - Type: GUID - Flags: PUBLIC
    ITEM_FIELD_GIFTCREATOR = EObjectFields.OBJECT_END + 0x6,                      // 0x00C - Size: 2 - Type: GUID - Flags: PUBLIC
    ITEM_FIELD_STACK_COUNT = EObjectFields.OBJECT_END + 0x8,                      // 0x00E - Size: 1 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_FIELD_DURATION = EObjectFields.OBJECT_END + 0x9,                         // 0x00F - Size: 1 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_FIELD_SPELL_CHARGES = EObjectFields.OBJECT_END + 0xA,                    // 0x010 - Size: 5 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_FIELD_FLAGS = EObjectFields.OBJECT_END + 0xF,                            // 0x015 - Size: 1 - Type: INT - Flags: PUBLIC
    ITEM_FIELD_ENCHANTMENT = EObjectFields.OBJECT_END + 0x10,                     // 0x016 - Size: 21 - Type: INT - Flags: PUBLIC
    ITEM_FIELD_PROPERTY_SEED = EObjectFields.OBJECT_END + 0x25,                   // 0x02B - Size: 1 - Type: INT - Flags: PUBLIC
    ITEM_FIELD_RANDOM_PROPERTIES_ID = EObjectFields.OBJECT_END + 0x26,            // 0x02C - Size: 1 - Type: INT - Flags: PUBLIC
    ITEM_FIELD_ITEM_TEXT_ID = EObjectFields.OBJECT_END + 0x27,                    // 0x02D - Size: 1 - Type: INT - Flags: OWNER_ONLY
    ITEM_FIELD_DURABILITY = EObjectFields.OBJECT_END + 0x28,                      // 0x02E - Size: 1 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_FIELD_MAXDURABILITY = EObjectFields.OBJECT_END + 0x29,                   // 0x02F - Size: 1 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_END = EObjectFields.OBJECT_END + 0x2A                                    // 0x030
}
Public Enum EContainerFields
{
    CONTAINER_FIELD_NUM_SLOTS = EItemFields.ITEM_END + 0x0,                       // 0x02A - Size: 1 - Type: INT - Flags: PUBLIC
    CONTAINER_ALIGN_PAD = EItemFields.ITEM_END + 0x1,                             // 0x02B - Size: 1 - Type: BYTES - Flags: NONE
    CONTAINER_FIELD_SLOT_1 = EItemFields.ITEM_END + 0x2,                          // 0x02C - Size: 72 - Type: GUID - Flags: PUBLIC
    CONTAINER_END = EItemFields.ITEM_END + 0x4A                                   // 0x074
}
Public Enum EUnitFields
{
    UNIT_FIELD_CHARM = EObjectFields.OBJECT_END + 0x0,                            // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_SUMMON = EObjectFields.OBJECT_END + 0x2,                           // 0x008 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_CHARMEDBY = EObjectFields.OBJECT_END + 0x4,                        // 0x00A - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_SUMMONEDBY = EObjectFields.OBJECT_END + 0x6,                       // 0x00C - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_CREATEDBY = EObjectFields.OBJECT_END + 0x8,                        // 0x00E - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_TARGET = EObjectFields.OBJECT_END + 0xA,                           // 0x010 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_PERSUADED = EObjectFields.OBJECT_END + 0xC,                        // 0x012 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_CHANNEL_OBJECT = EObjectFields.OBJECT_END + 0xE,                   // 0x014 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_HEALTH = EObjectFields.OBJECT_END + 0x10,                          // 0x016 - Size: 1 - Type: INT - Flags: DYNAMIC
    UNIT_FIELD_POWER1 = EObjectFields.OBJECT_END + 0x11,                          // 0x017 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_POWER2 = EObjectFields.OBJECT_END + 0x12,                          // 0x018 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_POWER3 = EObjectFields.OBJECT_END + 0x13,                          // 0x019 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_POWER4 = EObjectFields.OBJECT_END + 0x14,                          // 0x01A - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_POWER5 = EObjectFields.OBJECT_END + 0x15,                          // 0x01B - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXHEALTH = EObjectFields.OBJECT_END + 0x16,                       // 0x01C - Size: 1 - Type: INT - Flags: DYNAMIC
    UNIT_FIELD_MAXPOWER1 = EObjectFields.OBJECT_END + 0x17,                       // 0x01D - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXPOWER2 = EObjectFields.OBJECT_END + 0x18,                       // 0x01E - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXPOWER3 = EObjectFields.OBJECT_END + 0x19,                       // 0x01F - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXPOWER4 = EObjectFields.OBJECT_END + 0x1A,                       // 0x020 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXPOWER5 = EObjectFields.OBJECT_END + 0x1B,                       // 0x021 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_LEVEL = EObjectFields.OBJECT_END + 0x1C,                           // 0x022 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_FACTIONTEMPLATE = EObjectFields.OBJECT_END + 0x1D,                 // 0x023 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_BYTES_0 = EObjectFields.OBJECT_END + 0x1E,                         // 0x024 - Size: 1 - Type: BYTES - Flags: PUBLIC
    UNIT_VIRTUAL_ITEM_SLOT_DISPLAY = EObjectFields.OBJECT_END + 0x1F,             // 0x025 - Size: 3 - Type: INT - Flags: PUBLIC
    UNIT_VIRTUAL_ITEM_INFO = EObjectFields.OBJECT_END + 0x22,                     // 0x028 - Size: 6 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_FLAGS = EObjectFields.OBJECT_END + 0x28,                           // 0x02E - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_AURA = EObjectFields.OBJECT_END + 0x29,                            // 0x02F - Size: 48 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_AURAFLAGS = EObjectFields.OBJECT_END + 0x59,                       // 0x05F - Size: 6 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_AURALEVELS = EObjectFields.OBJECT_END + 0x5F,                      // 0x065 - Size: 12 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_AURAAPPLICATIONS = EObjectFields.OBJECT_END + 0x6B,                // 0x071 - Size: 12 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_AURASTATE = EObjectFields.OBJECT_END + 0x77,                       // 0x07D - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_BASEATTACKTIME = EObjectFields.OBJECT_END + 0x78,                  // 0x07E - Size: 2 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_RANGEDATTACKTIME = EObjectFields.OBJECT_END + 0x7A,                // 0x080 - Size: 1 - Type: INT - Flags: PRIVATE
    UNIT_FIELD_BOUNDINGRADIUS = EObjectFields.OBJECT_END + 0x7B,                  // 0x081 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    UNIT_FIELD_COMBATREACH = EObjectFields.OBJECT_END + 0x7C,                     // 0x082 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    UNIT_FIELD_DISPLAYID = EObjectFields.OBJECT_END + 0x7D,                       // 0x083 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_NATIVEDISPLAYID = EObjectFields.OBJECT_END + 0x7E,                 // 0x084 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MOUNTDISPLAYID = EObjectFields.OBJECT_END + 0x7F,                  // 0x085 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MINDAMAGE = EObjectFields.OBJECT_END + 0x80,                       // 0x086 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_MAXDAMAGE = EObjectFields.OBJECT_END + 0x81,                       // 0x087 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_MINOFFHANDDAMAGE = EObjectFields.OBJECT_END + 0x82,                // 0x088 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_MAXOFFHANDDAMAGE = EObjectFields.OBJECT_END + 0x83,                // 0x089 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_BYTES_1 = EObjectFields.OBJECT_END + 0x84,                         // 0x08A - Size: 1 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_PETNUMBER = EObjectFields.OBJECT_END + 0x85,                       // 0x08B - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_PET_NAME_TIMESTAMP = EObjectFields.OBJECT_END + 0x86,              // 0x08C - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_PETEXPERIENCE = EObjectFields.OBJECT_END + 0x87,                   // 0x08D - Size: 1 - Type: INT - Flags: OWNER_ONLY
    UNIT_FIELD_PETNEXTLEVELEXP = EObjectFields.OBJECT_END + 0x88,                 // 0x08E - Size: 1 - Type: INT - Flags: OWNER_ONLY
    UNIT_DYNAMIC_FLAGS = EObjectFields.OBJECT_END + 0x89,                         // 0x08F - Size: 1 - Type: INT - Flags: DYNAMIC
    UNIT_CHANNEL_SPELL = EObjectFields.OBJECT_END + 0x8A,                         // 0x090 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_MOD_CAST_SPEED = EObjectFields.OBJECT_END + 0x8B,                        // 0x091 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_CREATED_BY_SPELL = EObjectFields.OBJECT_END + 0x8C,                      // 0x092 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_NPC_FLAGS = EObjectFields.OBJECT_END + 0x8D,                             // 0x093 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_NPC_EMOTESTATE = EObjectFields.OBJECT_END + 0x8E,                        // 0x094 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_TRAINING_POINTS = EObjectFields.OBJECT_END + 0x8F,                       // 0x095 - Size: 1 - Type: TWO_SHORT - Flags: OWNER_ONLY
    UNIT_FIELD_STAT0 = EObjectFields.OBJECT_END + 0x90,                           // 0x096 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_STAT1 = EObjectFields.OBJECT_END + 0x91,                           // 0x097 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_STAT2 = EObjectFields.OBJECT_END + 0x92,                           // 0x098 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_STAT3 = EObjectFields.OBJECT_END + 0x93,                           // 0x099 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_STAT4 = EObjectFields.OBJECT_END + 0x94,                           // 0x09A - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RESISTANCES = EObjectFields.OBJECT_END + 0x95,                     // 0x09B - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_BASE_MANA = EObjectFields.OBJECT_END + 0x9C,                       // 0x0A2 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_BASE_HEALTH = EObjectFields.OBJECT_END + 0x9D,                     // 0x0A3 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_BYTES_2 = EObjectFields.OBJECT_END + 0x9E,                         // 0x0A4 - Size: 1 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_ATTACK_POWER = EObjectFields.OBJECT_END + 0x9F,                    // 0x0A5 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_ATTACK_POWER_MODS = EObjectFields.OBJECT_END + 0xA0,               // 0x0A6 - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_ATTACK_POWER_MULTIPLIER = EObjectFields.OBJECT_END + 0xA1,         // 0x0A7 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RANGED_ATTACK_POWER = EObjectFields.OBJECT_END + 0xA2,             // 0x0A8 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RANGED_ATTACK_POWER_MODS = EObjectFields.OBJECT_END + 0xA3,        // 0x0A9 - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = EObjectFields.OBJECT_END + 0xA4,  // 0x0AA - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_MINRANGEDDAMAGE = EObjectFields.OBJECT_END + 0xA5,                 // 0x0AB - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_MAXRANGEDDAMAGE = EObjectFields.OBJECT_END + 0xA6,                 // 0x0AC - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POWER_COST_MODIFIER = EObjectFields.OBJECT_END + 0xA7,             // 0x0AD - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POWER_COST_MULTIPLIER = EObjectFields.OBJECT_END + 0xAE,           // 0x0B4 - Size: 7 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_PADDING = EObjectFields.OBJECT_END + 0xB5,                         // 0x0BB - Size: 1 - Type: INT - Flags: NONE
    UNIT_END = EObjectFields.OBJECT_END + 0xB6                                    // 0x0BC
}
Public Enum EPlayerFields
{
    PLAYER_SELECTION = EUnitFields.UNIT_END + 0x0,                                // 0x0B6 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_DUEL_ARBITER = EUnitFields.UNIT_END + 0x2,                             // 0x0B8 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_FLAGS = EUnitFields.UNIT_END + 0x4,                                    // 0x0BA - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_GUILDID = EUnitFields.UNIT_END + 0x5,                                  // 0x0BB - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_GUILDRANK = EUnitFields.UNIT_END + 0x6,                                // 0x0BC - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_BYTES = EUnitFields.UNIT_END + 0x7,                                    // 0x0BD - Size: 1 - Type: BYTES - Flags: PUBLIC
    PLAYER_BYTES_2 = EUnitFields.UNIT_END + 0x8,                                  // 0x0BE - Size: 1 - Type: BYTES - Flags: PUBLIC
    PLAYER_BYTES_3 = EUnitFields.UNIT_END + 0x9,                                  // 0x0BF - Size: 1 - Type: BYTES - Flags: PUBLIC
    PLAYER_DUEL_TEAM = EUnitFields.UNIT_END + 0xA,                                // 0x0C0 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_GUILD_TIMESTAMP = EUnitFields.UNIT_END + 0xB,                          // 0x0C1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_QUEST_LOG_1_1 = EUnitFields.UNIT_END + 0xC,                            // 0x0C2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_1_2 = EUnitFields.UNIT_END + 0xD,                            // 0x0C3 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_2_1 = EUnitFields.UNIT_END + 0xF,                            // 0x0C5 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_2_2 = EUnitFields.UNIT_END + 0x10,                           // 0x0C6 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_3_1 = EUnitFields.UNIT_END + 0x12,                           // 0x0C8 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_3_2 = EUnitFields.UNIT_END + 0x13,                           // 0x0C9 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_4_1 = EUnitFields.UNIT_END + 0x15,                           // 0x0CB - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_4_2 = EUnitFields.UNIT_END + 0x16,                           // 0x0CC - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_5_1 = EUnitFields.UNIT_END + 0x18,                           // 0x0CE - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_5_2 = EUnitFields.UNIT_END + 0x19,                           // 0x0CF - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_6_1 = EUnitFields.UNIT_END + 0x1B,                           // 0x0D1 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_6_2 = EUnitFields.UNIT_END + 0x1C,                           // 0x0D2 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_7_1 = EUnitFields.UNIT_END + 0x1E,                           // 0x0D4 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_7_2 = EUnitFields.UNIT_END + 0x1F,                           // 0x0D5 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_8_1 = EUnitFields.UNIT_END + 0x21,                           // 0x0D7 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_8_2 = EUnitFields.UNIT_END + 0x22,                           // 0x0D8 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_9_1 = EUnitFields.UNIT_END + 0x24,                           // 0x0DA - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_9_2 = EUnitFields.UNIT_END + 0x25,                           // 0x0DB - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_10_1 = EUnitFields.UNIT_END + 0x27,                          // 0x0DD - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_10_2 = EUnitFields.UNIT_END + 0x28,                          // 0x0DE - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_11_1 = EUnitFields.UNIT_END + 0x2A,                          // 0x0E0 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_11_2 = EUnitFields.UNIT_END + 0x2B,                          // 0x0E1 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_12_1 = EUnitFields.UNIT_END + 0x2D,                          // 0x0E3 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_12_2 = EUnitFields.UNIT_END + 0x2E,                          // 0x0E4 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_13_1 = EUnitFields.UNIT_END + 0x30,                          // 0x0E6 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_13_2 = EUnitFields.UNIT_END + 0x31,                          // 0x0E7 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_14_1 = EUnitFields.UNIT_END + 0x33,                          // 0x0E9 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_14_2 = EUnitFields.UNIT_END + 0x34,                          // 0x0EA - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_15_1 = EUnitFields.UNIT_END + 0x36,                          // 0x0EC - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_15_2 = EUnitFields.UNIT_END + 0x37,                          // 0x0ED - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_16_1 = EUnitFields.UNIT_END + 0x39,                          // 0x0EF - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_16_2 = EUnitFields.UNIT_END + 0x3A,                          // 0x0F0 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_17_1 = EUnitFields.UNIT_END + 0x3C,                          // 0x0F2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_17_2 = EUnitFields.UNIT_END + 0x3D,                          // 0x0F3 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_18_1 = EUnitFields.UNIT_END + 0x3F,                          // 0x0F5 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_18_2 = EUnitFields.UNIT_END + 0x40,                          // 0x0F6 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_19_1 = EUnitFields.UNIT_END + 0x42,                          // 0x0F8 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_19_2 = EUnitFields.UNIT_END + 0x43,                          // 0x0F9 - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_20_1 = EUnitFields.UNIT_END + 0x45,                          // 0x0FB - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_20_2 = EUnitFields.UNIT_END + 0x46,                          // 0x0FC - Size: 2 - Type: INT - Flags: PRIVATE
    PLAYER_VISIBLE_ITEM_1_CREATOR = EUnitFields.UNIT_END + 0x48,                  // 0x0FE - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_1_0 = EUnitFields.UNIT_END + 0x4A,                        // 0x100 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_1_PROPERTIES = EUnitFields.UNIT_END + 0x52,               // 0x108 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_1_PAD = EUnitFields.UNIT_END + 0x53,                      // 0x109 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_2_CREATOR = EUnitFields.UNIT_END + 0x54,                  // 0x10A - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_2_0 = EUnitFields.UNIT_END + 0x56,                        // 0x10C - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_2_PROPERTIES = EUnitFields.UNIT_END + 0x5E,               // 0x114 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_2_PAD = EUnitFields.UNIT_END + 0x5F,                      // 0x115 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_3_CREATOR = EUnitFields.UNIT_END + 0x60,                  // 0x116 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_3_0 = EUnitFields.UNIT_END + 0x62,                        // 0x118 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_3_PROPERTIES = EUnitFields.UNIT_END + 0x6A,               // 0x120 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_3_PAD = EUnitFields.UNIT_END + 0x6B,                      // 0x121 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_4_CREATOR = EUnitFields.UNIT_END + 0x6C,                  // 0x122 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_4_0 = EUnitFields.UNIT_END + 0x6E,                        // 0x124 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_4_PROPERTIES = EUnitFields.UNIT_END + 0x76,               // 0x12C - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_4_PAD = EUnitFields.UNIT_END + 0x77,                      // 0x12D - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_5_CREATOR = EUnitFields.UNIT_END + 0x78,                  // 0x12E - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_5_0 = EUnitFields.UNIT_END + 0x7A,                        // 0x130 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_5_PROPERTIES = EUnitFields.UNIT_END + 0x82,               // 0x138 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_5_PAD = EUnitFields.UNIT_END + 0x83,                      // 0x139 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_6_CREATOR = EUnitFields.UNIT_END + 0x84,                  // 0x13A - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_6_0 = EUnitFields.UNIT_END + 0x86,                        // 0x13C - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_6_PROPERTIES = EUnitFields.UNIT_END + 0x8E,               // 0x144 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_6_PAD = EUnitFields.UNIT_END + 0x8F,                      // 0x145 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_7_CREATOR = EUnitFields.UNIT_END + 0x90,                  // 0x146 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_7_0 = EUnitFields.UNIT_END + 0x92,                        // 0x148 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_7_PROPERTIES = EUnitFields.UNIT_END + 0x9A,               // 0x150 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_7_PAD = EUnitFields.UNIT_END + 0x9B,                      // 0x151 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_8_CREATOR = EUnitFields.UNIT_END + 0x9C,                  // 0x152 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_8_0 = EUnitFields.UNIT_END + 0x9E,                        // 0x154 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_8_PROPERTIES = EUnitFields.UNIT_END + 0xA6,               // 0x15C - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_8_PAD = EUnitFields.UNIT_END + 0xA7,                      // 0x15D - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_9_CREATOR = EUnitFields.UNIT_END + 0xA8,                  // 0x15E - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_9_0 = EUnitFields.UNIT_END + 0xAA,                        // 0x160 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_9_PROPERTIES = EUnitFields.UNIT_END + 0xB2,               // 0x168 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_9_PAD = EUnitFields.UNIT_END + 0xB3,                      // 0x169 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_10_CREATOR = EUnitFields.UNIT_END + 0xB4,                 // 0x16A - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_10_0 = EUnitFields.UNIT_END + 0xB6,                       // 0x16C - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_10_PROPERTIES = EUnitFields.UNIT_END + 0xBE,              // 0x174 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_10_PAD = EUnitFields.UNIT_END + 0xBF,                     // 0x175 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_11_CREATOR = EUnitFields.UNIT_END + 0xC0,                 // 0x176 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_11_0 = EUnitFields.UNIT_END + 0xC2,                       // 0x178 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_11_PROPERTIES = EUnitFields.UNIT_END + 0xCA,              // 0x180 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_11_PAD = EUnitFields.UNIT_END + 0xCB,                     // 0x181 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_12_CREATOR = EUnitFields.UNIT_END + 0xCC,                 // 0x182 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_12_0 = EUnitFields.UNIT_END + 0xCE,                       // 0x184 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_12_PROPERTIES = EUnitFields.UNIT_END + 0xD6,              // 0x18C - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_12_PAD = EUnitFields.UNIT_END + 0xD7,                     // 0x18D - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_13_CREATOR = EUnitFields.UNIT_END + 0xD8,                 // 0x18E - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_13_0 = EUnitFields.UNIT_END + 0xDA,                       // 0x190 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_13_PROPERTIES = EUnitFields.UNIT_END + 0xE2,              // 0x198 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_13_PAD = EUnitFields.UNIT_END + 0xE3,                     // 0x199 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_14_CREATOR = EUnitFields.UNIT_END + 0xE4,                 // 0x19A - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_14_0 = EUnitFields.UNIT_END + 0xE6,                       // 0x19C - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_14_PROPERTIES = EUnitFields.UNIT_END + 0xEE,              // 0x1A4 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_14_PAD = EUnitFields.UNIT_END + 0xEF,                     // 0x1A5 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_15_CREATOR = EUnitFields.UNIT_END + 0xF0,                 // 0x1A6 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_15_0 = EUnitFields.UNIT_END + 0xF2,                       // 0x1A8 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_15_PROPERTIES = EUnitFields.UNIT_END + 0xFA,              // 0x1B0 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_15_PAD = EUnitFields.UNIT_END + 0xFB,                     // 0x1B1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_16_CREATOR = EUnitFields.UNIT_END + 0xFC,                 // 0x1B2 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_16_0 = EUnitFields.UNIT_END + 0xFE,                       // 0x1B4 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_16_PROPERTIES = EUnitFields.UNIT_END + 0x106,             // 0x1BC - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_16_PAD = EUnitFields.UNIT_END + 0x107,                    // 0x1BD - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_17_CREATOR = EUnitFields.UNIT_END + 0x108,                // 0x1BE - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_17_0 = EUnitFields.UNIT_END + 0x10A,                      // 0x1C0 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_17_PROPERTIES = EUnitFields.UNIT_END + 0x112,             // 0x1C8 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_17_PAD = EUnitFields.UNIT_END + 0x113,                    // 0x1C9 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_18_CREATOR = EUnitFields.UNIT_END + 0x114,                // 0x1CA - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_18_0 = EUnitFields.UNIT_END + 0x116,                      // 0x1CC - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_18_PROPERTIES = EUnitFields.UNIT_END + 0x11E,             // 0x1D4 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_18_PAD = EUnitFields.UNIT_END + 0x11F,                    // 0x1D5 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_19_CREATOR = EUnitFields.UNIT_END + 0x120,                // 0x1D6 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_19_0 = EUnitFields.UNIT_END + 0x122,                      // 0x1D8 - Size: 8 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_19_PROPERTIES = EUnitFields.UNIT_END + 0x12A,             // 0x1E0 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_19_PAD = EUnitFields.UNIT_END + 0x12B,                    // 0x1E1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_FIELD_INV_SLOT_HEAD = EUnitFields.UNIT_END + 0x12C,                    // 0x1E2 - Size: 46 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_PACK_SLOT_1 = EUnitFields.UNIT_END + 0x15A,                      // 0x210 - Size: 32 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_BANK_SLOT_1 = EUnitFields.UNIT_END + 0x17A,                      // 0x230 - Size: 48 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_BANKBAG_SLOT_1 = EUnitFields.UNIT_END + 0x1AA,                   // 0x260 - Size: 12 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_VENDORBUYBACK_SLOT_1 = EUnitFields.UNIT_END + 0x1B6,             // 0x26C - Size: 24 - Type: GUID - Flags: PRIVATE
    PLAYER_FARSIGHT = EUnitFields.UNIT_END + 0x1CE,                               // 0x284 - Size: 2 - Type: GUID - Flags: PRIVATE
    PLAYER__FIELD_COMBO_TARGET = EUnitFields.UNIT_END + 0x1D0,                    // 0x286 - Size: 2 - Type: GUID - Flags: PRIVATE
    PLAYER_XP = EUnitFields.UNIT_END + 0x1D2,                                     // 0x288 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_NEXT_LEVEL_XP = EUnitFields.UNIT_END + 0x1D3,                          // 0x289 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_SKILL_INFO_1_1 = EUnitFields.UNIT_END + 0x1D4,                         // 0x28A - Size: 384 - Type: TWO_SHORT - Flags: PRIVATE
    PLAYER_CHARACTER_POINTS1 = EUnitFields.UNIT_END + 0x354,                      // 0x40A - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_CHARACTER_POINTS2 = EUnitFields.UNIT_END + 0x355,                      // 0x40B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_TRACK_CREATURES = EUnitFields.UNIT_END + 0x356,                        // 0x40C - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_TRACK_RESOURCES = EUnitFields.UNIT_END + 0x357,                        // 0x40D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_BLOCK_PERCENTAGE = EUnitFields.UNIT_END + 0x358,                       // 0x40E - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_DODGE_PERCENTAGE = EUnitFields.UNIT_END + 0x359,                       // 0x40F - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_PARRY_PERCENTAGE = EUnitFields.UNIT_END + 0x35A,                       // 0x410 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_CRIT_PERCENTAGE = EUnitFields.UNIT_END + 0x35B,                        // 0x411 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_RANGED_CRIT_PERCENTAGE = EUnitFields.UNIT_END + 0x35C,                 // 0x412 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_EXPLORED_ZONES_1 = EUnitFields.UNIT_END + 0x35D,                       // 0x413 - Size: 64 - Type: BYTES - Flags: PRIVATE
    PLAYER_REST_STATE_EXPERIENCE = EUnitFields.UNIT_END + 0x39D,                  // 0x453 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_COINAGE = EUnitFields.UNIT_END + 0x39E,                          // 0x454 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_POSSTAT0 = EUnitFields.UNIT_END + 0x39F,                         // 0x455 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_POSSTAT1 = EUnitFields.UNIT_END + 0x3A0,                         // 0x456 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_POSSTAT2 = EUnitFields.UNIT_END + 0x3A1,                         // 0x457 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_POSSTAT3 = EUnitFields.UNIT_END + 0x3A2,                         // 0x458 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_POSSTAT4 = EUnitFields.UNIT_END + 0x3A3,                         // 0x459 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_NEGSTAT0 = EUnitFields.UNIT_END + 0x3A4,                         // 0x45A - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_NEGSTAT1 = EUnitFields.UNIT_END + 0x3A5,                         // 0x45B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_NEGSTAT2 = EUnitFields.UNIT_END + 0x3A6,                         // 0x45C - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_NEGSTAT3 = EUnitFields.UNIT_END + 0x3A7,                         // 0x45D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_NEGSTAT4 = EUnitFields.UNIT_END + 0x3A8,                         // 0x45E - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_RESISTANCEBUFFMODSPOSITIVE = EUnitFields.UNIT_END + 0x3A9,       // 0x45F - Size: 7 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_RESISTANCEBUFFMODSNEGATIVE = EUnitFields.UNIT_END + 0x3B0,       // 0x466 - Size: 7 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_DAMAGE_DONE_POS = EUnitFields.UNIT_END + 0x3B7,              // 0x46D - Size: 7 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_DAMAGE_DONE_NEG = EUnitFields.UNIT_END + 0x3BE,              // 0x474 - Size: 7 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_DAMAGE_DONE_PCT = EUnitFields.UNIT_END + 0x3C5,              // 0x47B - Size: 7 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_BYTES = EUnitFields.UNIT_END + 0x3CC,                            // 0x482 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_AMMO_ID = EUnitFields.UNIT_END + 0x3CD,                                // 0x483 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_SELF_RES_SPELL = EUnitFields.UNIT_END + 0x3CE,                         // 0x484 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_PVP_MEDALS = EUnitFields.UNIT_END + 0x3CF,                       // 0x485 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_BUYBACK_PRICE_1 = EUnitFields.UNIT_END + 0x3D0,                  // 0x486 - Size: 12 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = EUnitFields.UNIT_END + 0x3DC,              // 0x492 - Size: 12 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_SESSION_KILLS = EUnitFields.UNIT_END + 0x3E8,                    // 0x49E - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE
    PLAYER_FIELD_YESTERDAY_KILLS = EUnitFields.UNIT_END + 0x3E9,                  // 0x49F - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE
    PLAYER_FIELD_LAST_WEEK_KILLS = EUnitFields.UNIT_END + 0x3EA,                  // 0x4A0 - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE
    PLAYER_FIELD_THIS_WEEK_KILLS = EUnitFields.UNIT_END + 0x3EB,                  // 0x4A1 - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE
    PLAYER_FIELD_THIS_WEEK_CONTRIBUTION = EUnitFields.UNIT_END + 0x3EC,           // 0x4A2 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_LIFETIME_HONORBALE_KILLS = EUnitFields.UNIT_END + 0x3ED,         // 0x4A3 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_LIFETIME_DISHONORBALE_KILLS = EUnitFields.UNIT_END + 0x3EE,      // 0x4A4 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_YESTERDAY_CONTRIBUTION = EUnitFields.UNIT_END + 0x3EF,           // 0x4A5 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_LAST_WEEK_CONTRIBUTION = EUnitFields.UNIT_END + 0x3F0,           // 0x4A6 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_LAST_WEEK_RANK = EUnitFields.UNIT_END + 0x3F1,                   // 0x4A7 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_BYTES2 = EUnitFields.UNIT_END + 0x3F2,                           // 0x4A8 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_FIELD_WATCHED_FACTION_INDEX = EUnitFields.UNIT_END + 0x3F3,            // 0x4A9 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_END = EUnitFields.UNIT_END + 0x3F4                                     // 0x4AA
}
Public Enum EGameObjectFields
{
    OBJECT_FIELD_CREATED_BY = EObjectFields.OBJECT_END + 0x0,                     // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    GAMEOBJECT_DISPLAYID = EObjectFields.OBJECT_END + 0x2,                        // 0x008 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_FLAGS = EObjectFields.OBJECT_END + 0x3,                            // 0x009 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_ROTATION = EObjectFields.OBJECT_END + 0x4,                         // 0x00A - Size: 4 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_STATE = EObjectFields.OBJECT_END + 0x8,                            // 0x00E - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_TIMESTAMP = EObjectFields.OBJECT_END + 0x9,                        // 0x00F - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_POS_X = EObjectFields.OBJECT_END + 0xA,                            // 0x010 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_POS_Y = EObjectFields.OBJECT_END + 0xB,                            // 0x011 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_POS_Z = EObjectFields.OBJECT_END + 0xC,                            // 0x012 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_FACING = EObjectFields.OBJECT_END + 0xD,                           // 0x013 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_DYN_FLAGS = EObjectFields.OBJECT_END + 0xE,                        // 0x014 - Size: 1 - Type: INT - Flags: DYNAMIC
    GAMEOBJECT_FACTION = EObjectFields.OBJECT_END + 0xF,                          // 0x015 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_TYPE_ID = EObjectFields.OBJECT_END + 0x10,                         // 0x016 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_LEVEL = EObjectFields.OBJECT_END + 0x11,                           // 0x017 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_END = EObjectFields.OBJECT_END + 0x12                              // 0x018
}
Public Enum EDynamicObjectFields
{
    DYNAMICOBJECT_CASTER = EObjectFields.OBJECT_END + 0x0,                        // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    DYNAMICOBJECT_BYTES = EObjectFields.OBJECT_END + 0x2,                         // 0x008 - Size: 1 - Type: BYTES - Flags: PUBLIC
    DYNAMICOBJECT_SPELLID = EObjectFields.OBJECT_END + 0x3,                       // 0x009 - Size: 1 - Type: INT - Flags: PUBLIC
    DYNAMICOBJECT_RADIUS = EObjectFields.OBJECT_END + 0x4,                        // 0x00A - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_POS_X = EObjectFields.OBJECT_END + 0x5,                         // 0x00B - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_POS_Y = EObjectFields.OBJECT_END + 0x6,                         // 0x00C - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_POS_Z = EObjectFields.OBJECT_END + 0x7,                         // 0x00D - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_FACING = EObjectFields.OBJECT_END + 0x8,                        // 0x00E - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_PAD = EObjectFields.OBJECT_END + 0x9,                           // 0x00F - Size: 1 - Type: BYTES - Flags: PUBLIC
    DYNAMICOBJECT_END = EObjectFields.OBJECT_END + 0xA                            // 0x010
}
Public Enum ECorpseFields
{
    CORPSE_FIELD_OWNER = EObjectFields.OBJECT_END + 0x0,                          // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    CORPSE_FIELD_FACING = EObjectFields.OBJECT_END + 0x2,                         // 0x008 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    CORPSE_FIELD_POS_X = EObjectFields.OBJECT_END + 0x3,                          // 0x009 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    CORPSE_FIELD_POS_Y = EObjectFields.OBJECT_END + 0x4,                          // 0x00A - Size: 1 - Type: FLOAT - Flags: PUBLIC
    CORPSE_FIELD_POS_Z = EObjectFields.OBJECT_END + 0x5,                          // 0x00B - Size: 1 - Type: FLOAT - Flags: PUBLIC
    CORPSE_FIELD_DISPLAY_ID = EObjectFields.OBJECT_END + 0x6,                     // 0x00C - Size: 1 - Type: INT - Flags: PUBLIC
    CORPSE_FIELD_ITEM = EObjectFields.OBJECT_END + 0x7,                           // 0x00D - Size: 19 - Type: INT - Flags: PUBLIC
    CORPSE_FIELD_BYTES_1 = EObjectFields.OBJECT_END + 0x1A,                       // 0x020 - Size: 1 - Type: BYTES - Flags: PUBLIC
    CORPSE_FIELD_BYTES_2 = EObjectFields.OBJECT_END + 0x1B,                       // 0x021 - Size: 1 - Type: BYTES - Flags: PUBLIC
    CORPSE_FIELD_GUILD = EObjectFields.OBJECT_END + 0x1C,                         // 0x022 - Size: 1 - Type: INT - Flags: PUBLIC
    CORPSE_FIELD_FLAGS = EObjectFields.OBJECT_END + 0x1D,                         // 0x023 - Size: 1 - Type: INT - Flags: PUBLIC
    CORPSE_FIELD_DYNAMIC_FLAGS = EObjectFields.OBJECT_END + 0x1E,                 // 0x024 - Size: 1 - Type: INT - Flags: DYNAMIC
    CORPSE_FIELD_PAD = EObjectFields.OBJECT_END + 0x1F,                           // 0x025 - Size: 1 - Type: INT - Flags: NONE
    CORPSE_END = EObjectFields.OBJECT_END + 0x20                                  // 0x026
}
