// Auto generated file
// Patch: 2.4.2
// Build: 8278

Public Enum EObjectFields
{
    OBJECT_FIELD_GUID = 0x0,                                                      // 0x000 - Size: 2 - Type: GUID - Flags: PUBLIC
    OBJECT_FIELD_TYPE = 0x2,                                                      // 0x002 - Size: 1 - Type: INT - Flags: PUBLIC
    OBJECT_FIELD_ENTRY = 0x3,                                                     // 0x003 - Size: 1 - Type: INT - Flags: PUBLIC
    OBJECT_FIELD_SCALE_X = 0x4,                                                   // 0x004 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    OBJECT_FIELD_PADDING = 0x5,                                                   // 0x005 - Size: 1 - Type: INT - Flags: NONE
    OBJECT_END = 0x6                                                              
}
Public Enum EContainerFields
{
    CONTAINER_FIELD_NUM_SLOTS = EItemFields.ITEM_END + 0x0,                       // 0x036 - Size: 1 - Type: INT - Flags: PUBLIC
    CONTAINER_ALIGN_PAD = EItemFields.ITEM_END + 0x1,                             // 0x037 - Size: 1 - Type: BYTES - Flags: NONE
    CONTAINER_FIELD_SLOT_1 = EItemFields.ITEM_END + 0x2,                          // 0x038 - Size: 72 - Type: GUID - Flags: PUBLIC
    CONTAINER_END = EItemFields.ITEM_END + 0x4A                                   // 0x080
}
Public Enum EItemFields
{
    ITEM_FIELD_OWNER = EObjectFields.OBJECT_END + 0x0,                            // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    ITEM_FIELD_CONTAINED = EObjectFields.OBJECT_END + 0x2,                        // 0x008 - Size: 2 - Type: GUID - Flags: PUBLIC
    ITEM_FIELD_CREATOR = EObjectFields.OBJECT_END + 0x4,                          // 0x00A - Size: 2 - Type: GUID - Flags: PUBLIC
    ITEM_FIELD_GIFTCREATOR = EObjectFields.OBJECT_END + 0x6,                      // 0x00C - Size: 2 - Type: GUID - Flags: PUBLIC
    ITEM_FIELD_STACK_COUNT = EObjectFields.OBJECT_END + 0x8,                      // 0x00E - Size: 1 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_FIELD_DURATION = EObjectFields.OBJECT_END + 0x9,                         // 0x00F - Size: 1 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_FIELD_SPELL_CHARGES = EObjectFields.OBJECT_END + 0xA,                    // 0x010 - Size: 5 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_FIELD_FLAGS = EObjectFields.OBJECT_END + 0xF,                            // 0x015 - Size: 1 - Type: INT - Flags: PUBLIC
    ITEM_FIELD_ENCHANTMENT = EObjectFields.OBJECT_END + 0x10,                     // 0x016 - Size: 33 - Type: INT - Flags: PUBLIC
    ITEM_FIELD_PROPERTY_SEED = EObjectFields.OBJECT_END + 0x31,                   // 0x037 - Size: 1 - Type: INT - Flags: PUBLIC
    ITEM_FIELD_RANDOM_PROPERTIES_ID = EObjectFields.OBJECT_END + 0x32,            // 0x038 - Size: 1 - Type: INT - Flags: PUBLIC
    ITEM_FIELD_ITEM_TEXT_ID = EObjectFields.OBJECT_END + 0x33,                    // 0x039 - Size: 1 - Type: INT - Flags: OWNER_ONLY
    ITEM_FIELD_DURABILITY = EObjectFields.OBJECT_END + 0x34,                      // 0x03A - Size: 1 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_FIELD_MAXDURABILITY = EObjectFields.OBJECT_END + 0x35,                   // 0x03B - Size: 1 - Type: INT - Flags: OWNER_ONLY + UNK2
    ITEM_END = EObjectFields.OBJECT_END + 0x36                                    // 0x03C
}
Public Enum EUnitFields
{
    UNIT_FIELD_CHARM = EObjectFields.OBJECT_END + 0x0,                            // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_SUMMON = EObjectFields.OBJECT_END + 0x2,                           // 0x008 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_CHARMEDBY = EObjectFields.OBJECT_END + 0x4,                        // 0x00A - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_SUMMONEDBY = EObjectFields.OBJECT_END + 0x6,                       // 0x00C - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_CREATEDBY = EObjectFields.OBJECT_END + 0x8,                        // 0x00E - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_TARGET = EObjectFields.OBJECT_END + 0xA,                           // 0x010 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_PERSUADED = EObjectFields.OBJECT_END + 0xC,                        // 0x012 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_CHANNEL_OBJECT = EObjectFields.OBJECT_END + 0xE,                   // 0x014 - Size: 2 - Type: GUID - Flags: PUBLIC
    UNIT_FIELD_HEALTH = EObjectFields.OBJECT_END + 0x10,                          // 0x016 - Size: 1 - Type: INT - Flags: DYNAMIC
    UNIT_FIELD_POWER1 = EObjectFields.OBJECT_END + 0x11,                          // 0x017 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_POWER2 = EObjectFields.OBJECT_END + 0x12,                          // 0x018 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_POWER3 = EObjectFields.OBJECT_END + 0x13,                          // 0x019 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_POWER4 = EObjectFields.OBJECT_END + 0x14,                          // 0x01A - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_POWER5 = EObjectFields.OBJECT_END + 0x15,                          // 0x01B - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXHEALTH = EObjectFields.OBJECT_END + 0x16,                       // 0x01C - Size: 1 - Type: INT - Flags: DYNAMIC
    UNIT_FIELD_MAXPOWER1 = EObjectFields.OBJECT_END + 0x17,                       // 0x01D - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXPOWER2 = EObjectFields.OBJECT_END + 0x18,                       // 0x01E - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXPOWER3 = EObjectFields.OBJECT_END + 0x19,                       // 0x01F - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXPOWER4 = EObjectFields.OBJECT_END + 0x1A,                       // 0x020 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MAXPOWER5 = EObjectFields.OBJECT_END + 0x1B,                       // 0x021 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_LEVEL = EObjectFields.OBJECT_END + 0x1C,                           // 0x022 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_FACTIONTEMPLATE = EObjectFields.OBJECT_END + 0x1D,                 // 0x023 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_BYTES_0 = EObjectFields.OBJECT_END + 0x1E,                         // 0x024 - Size: 1 - Type: BYTES - Flags: PUBLIC
    UNIT_VIRTUAL_ITEM_SLOT_DISPLAY = EObjectFields.OBJECT_END + 0x1F,             // 0x025 - Size: 3 - Type: INT - Flags: PUBLIC
    UNIT_VIRTUAL_ITEM_INFO = EObjectFields.OBJECT_END + 0x22,                     // 0x028 - Size: 6 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_FLAGS = EObjectFields.OBJECT_END + 0x28,                           // 0x02E - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_FLAGS_2 = EObjectFields.OBJECT_END + 0x29,                         // 0x02F - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_AURA = EObjectFields.OBJECT_END + 0x2A,                            // 0x030 - Size: 56 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_AURAFLAGS = EObjectFields.OBJECT_END + 0x62,                       // 0x068 - Size: 14 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_AURALEVELS = EObjectFields.OBJECT_END + 0x70,                      // 0x076 - Size: 14 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_AURAAPPLICATIONS = EObjectFields.OBJECT_END + 0x7E,                // 0x084 - Size: 14 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_AURASTATE = EObjectFields.OBJECT_END + 0x8C,                       // 0x092 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_BASEATTACKTIME = EObjectFields.OBJECT_END + 0x8D,                  // 0x093 - Size: 2 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_RANGEDATTACKTIME = EObjectFields.OBJECT_END + 0x8F,                // 0x095 - Size: 1 - Type: INT - Flags: PRIVATE
    UNIT_FIELD_BOUNDINGRADIUS = EObjectFields.OBJECT_END + 0x90,                  // 0x096 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    UNIT_FIELD_COMBATREACH = EObjectFields.OBJECT_END + 0x91,                     // 0x097 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    UNIT_FIELD_DISPLAYID = EObjectFields.OBJECT_END + 0x92,                       // 0x098 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_NATIVEDISPLAYID = EObjectFields.OBJECT_END + 0x93,                 // 0x099 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MOUNTDISPLAYID = EObjectFields.OBJECT_END + 0x94,                  // 0x09A - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_MINDAMAGE = EObjectFields.OBJECT_END + 0x95,                       // 0x09B - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_MAXDAMAGE = EObjectFields.OBJECT_END + 0x96,                       // 0x09C - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_MINOFFHANDDAMAGE = EObjectFields.OBJECT_END + 0x97,                // 0x09D - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_MAXOFFHANDDAMAGE = EObjectFields.OBJECT_END + 0x98,                // 0x09E - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_BYTES_1 = EObjectFields.OBJECT_END + 0x99,                         // 0x09F - Size: 1 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_PETNUMBER = EObjectFields.OBJECT_END + 0x9A,                       // 0x0A0 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_PET_NAME_TIMESTAMP = EObjectFields.OBJECT_END + 0x9B,              // 0x0A1 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_FIELD_PETEXPERIENCE = EObjectFields.OBJECT_END + 0x9C,                   // 0x0A2 - Size: 1 - Type: INT - Flags: OWNER_ONLY
    UNIT_FIELD_PETNEXTLEVELEXP = EObjectFields.OBJECT_END + 0x9D,                 // 0x0A3 - Size: 1 - Type: INT - Flags: OWNER_ONLY
    UNIT_DYNAMIC_FLAGS = EObjectFields.OBJECT_END + 0x9E,                         // 0x0A4 - Size: 1 - Type: INT - Flags: DYNAMIC
    UNIT_CHANNEL_SPELL = EObjectFields.OBJECT_END + 0x9F,                         // 0x0A5 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_MOD_CAST_SPEED = EObjectFields.OBJECT_END + 0xA0,                        // 0x0A6 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    UNIT_CREATED_BY_SPELL = EObjectFields.OBJECT_END + 0xA1,                      // 0x0A7 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_NPC_FLAGS = EObjectFields.OBJECT_END + 0xA2,                             // 0x0A8 - Size: 1 - Type: INT - Flags: DYNAMIC
    UNIT_NPC_EMOTESTATE = EObjectFields.OBJECT_END + 0xA3,                        // 0x0A9 - Size: 1 - Type: INT - Flags: PUBLIC
    UNIT_TRAINING_POINTS = EObjectFields.OBJECT_END + 0xA4,                       // 0x0AA - Size: 1 - Type: TWO_SHORT - Flags: OWNER_ONLY
    UNIT_FIELD_STAT0 = EObjectFields.OBJECT_END + 0xA5,                           // 0x0AB - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_STAT1 = EObjectFields.OBJECT_END + 0xA6,                           // 0x0AC - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_STAT2 = EObjectFields.OBJECT_END + 0xA7,                           // 0x0AD - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_STAT3 = EObjectFields.OBJECT_END + 0xA8,                           // 0x0AE - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_STAT4 = EObjectFields.OBJECT_END + 0xA9,                           // 0x0AF - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POSSTAT0 = EObjectFields.OBJECT_END + 0xAA,                        // 0x0B0 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POSSTAT1 = EObjectFields.OBJECT_END + 0xAB,                        // 0x0B1 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POSSTAT2 = EObjectFields.OBJECT_END + 0xAC,                        // 0x0B2 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POSSTAT3 = EObjectFields.OBJECT_END + 0xAD,                        // 0x0B3 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POSSTAT4 = EObjectFields.OBJECT_END + 0xAE,                        // 0x0B4 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_NEGSTAT0 = EObjectFields.OBJECT_END + 0xAF,                        // 0x0B5 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_NEGSTAT1 = EObjectFields.OBJECT_END + 0xB0,                        // 0x0B6 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_NEGSTAT2 = EObjectFields.OBJECT_END + 0xB1,                        // 0x0B7 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_NEGSTAT3 = EObjectFields.OBJECT_END + 0xB2,                        // 0x0B8 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_NEGSTAT4 = EObjectFields.OBJECT_END + 0xB3,                        // 0x0B9 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RESISTANCES = EObjectFields.OBJECT_END + 0xB4,                     // 0x0BA - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY + UNK3
    UNIT_FIELD_RESISTANCEBUFFMODSPOSITIVE = EObjectFields.OBJECT_END + 0xBB,      // 0x0C1 - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RESISTANCEBUFFMODSNEGATIVE = EObjectFields.OBJECT_END + 0xC2,      // 0x0C8 - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_BASE_MANA = EObjectFields.OBJECT_END + 0xC9,                       // 0x0CF - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_BASE_HEALTH = EObjectFields.OBJECT_END + 0xCA,                     // 0x0D0 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_BYTES_2 = EObjectFields.OBJECT_END + 0xCB,                         // 0x0D1 - Size: 1 - Type: BYTES - Flags: PUBLIC
    UNIT_FIELD_ATTACK_POWER = EObjectFields.OBJECT_END + 0xCC,                    // 0x0D2 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_ATTACK_POWER_MODS = EObjectFields.OBJECT_END + 0xCD,               // 0x0D3 - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_ATTACK_POWER_MULTIPLIER = EObjectFields.OBJECT_END + 0xCE,         // 0x0D4 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RANGED_ATTACK_POWER = EObjectFields.OBJECT_END + 0xCF,             // 0x0D5 - Size: 1 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RANGED_ATTACK_POWER_MODS = EObjectFields.OBJECT_END + 0xD0,        // 0x0D6 - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_RANGED_ATTACK_POWER_MULTIPLIER = EObjectFields.OBJECT_END + 0xD1,  // 0x0D7 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_MINRANGEDDAMAGE = EObjectFields.OBJECT_END + 0xD2,                 // 0x0D8 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_MAXRANGEDDAMAGE = EObjectFields.OBJECT_END + 0xD3,                 // 0x0D9 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POWER_COST_MODIFIER = EObjectFields.OBJECT_END + 0xD4,             // 0x0DA - Size: 7 - Type: INT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_POWER_COST_MULTIPLIER = EObjectFields.OBJECT_END + 0xDB,           // 0x0E1 - Size: 7 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_MAXHEALTHMODIFIER = EObjectFields.OBJECT_END + 0xE2,               // 0x0E8 - Size: 1 - Type: FLOAT - Flags: PRIVATE + OWNER_ONLY
    UNIT_FIELD_PADDING = EObjectFields.OBJECT_END + 0xE3,                         // 0x0E9 - Size: 1 - Type: INT - Flags: NONE
    UNIT_END = EObjectFields.OBJECT_END + 0xE4                                    // 0x0EA
}
Public Enum EPlayerFields
{
    PLAYER_DUEL_ARBITER = EUnitFields.UNIT_END + 0x0,                             // 0x0E4 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_FLAGS = EUnitFields.UNIT_END + 0x2,                                    // 0x0E6 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_GUILDID = EUnitFields.UNIT_END + 0x3,                                  // 0x0E7 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_GUILDRANK = EUnitFields.UNIT_END + 0x4,                                // 0x0E8 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_BYTES = EUnitFields.UNIT_END + 0x5,                                    // 0x0E9 - Size: 1 - Type: BYTES - Flags: PUBLIC
    PLAYER_BYTES_2 = EUnitFields.UNIT_END + 0x6,                                  // 0x0EA - Size: 1 - Type: BYTES - Flags: PUBLIC
    PLAYER_BYTES_3 = EUnitFields.UNIT_END + 0x7,                                  // 0x0EB - Size: 1 - Type: BYTES - Flags: PUBLIC
    PLAYER_DUEL_TEAM = EUnitFields.UNIT_END + 0x8,                                // 0x0EC - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_GUILD_TIMESTAMP = EUnitFields.UNIT_END + 0x9,                          // 0x0ED - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_QUEST_LOG_1_1 = EUnitFields.UNIT_END + 0xA,                            // 0x0EE - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_1_2 = EUnitFields.UNIT_END + 0xB,                            // 0x0EF - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_1_3 = EUnitFields.UNIT_END + 0xC,                            // 0x0F0 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_1_4 = EUnitFields.UNIT_END + 0xD,                            // 0x0F1 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_2_1 = EUnitFields.UNIT_END + 0xE,                            // 0x0F2 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_2_2 = EUnitFields.UNIT_END + 0xF,                            // 0x0F3 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_2_3 = EUnitFields.UNIT_END + 0x10,                           // 0x0F4 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_2_4 = EUnitFields.UNIT_END + 0x11,                           // 0x0F5 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_3_1 = EUnitFields.UNIT_END + 0x12,                           // 0x0F6 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_3_2 = EUnitFields.UNIT_END + 0x13,                           // 0x0F7 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_3_3 = EUnitFields.UNIT_END + 0x14,                           // 0x0F8 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_3_4 = EUnitFields.UNIT_END + 0x15,                           // 0x0F9 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_4_1 = EUnitFields.UNIT_END + 0x16,                           // 0x0FA - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_4_2 = EUnitFields.UNIT_END + 0x17,                           // 0x0FB - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_4_3 = EUnitFields.UNIT_END + 0x18,                           // 0x0FC - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_4_4 = EUnitFields.UNIT_END + 0x19,                           // 0x0FD - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_5_1 = EUnitFields.UNIT_END + 0x1A,                           // 0x0FE - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_5_2 = EUnitFields.UNIT_END + 0x1B,                           // 0x0FF - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_5_3 = EUnitFields.UNIT_END + 0x1C,                           // 0x100 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_5_4 = EUnitFields.UNIT_END + 0x1D,                           // 0x101 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_6_1 = EUnitFields.UNIT_END + 0x1E,                           // 0x102 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_6_2 = EUnitFields.UNIT_END + 0x1F,                           // 0x103 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_6_3 = EUnitFields.UNIT_END + 0x20,                           // 0x104 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_6_4 = EUnitFields.UNIT_END + 0x21,                           // 0x105 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_7_1 = EUnitFields.UNIT_END + 0x22,                           // 0x106 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_7_2 = EUnitFields.UNIT_END + 0x23,                           // 0x107 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_7_3 = EUnitFields.UNIT_END + 0x24,                           // 0x108 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_7_4 = EUnitFields.UNIT_END + 0x25,                           // 0x109 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_8_1 = EUnitFields.UNIT_END + 0x26,                           // 0x10A - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_8_2 = EUnitFields.UNIT_END + 0x27,                           // 0x10B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_8_3 = EUnitFields.UNIT_END + 0x28,                           // 0x10C - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_8_4 = EUnitFields.UNIT_END + 0x29,                           // 0x10D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_9_1 = EUnitFields.UNIT_END + 0x2A,                           // 0x10E - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_9_2 = EUnitFields.UNIT_END + 0x2B,                           // 0x10F - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_9_3 = EUnitFields.UNIT_END + 0x2C,                           // 0x110 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_9_4 = EUnitFields.UNIT_END + 0x2D,                           // 0x111 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_10_1 = EUnitFields.UNIT_END + 0x2E,                          // 0x112 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_10_2 = EUnitFields.UNIT_END + 0x2F,                          // 0x113 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_10_3 = EUnitFields.UNIT_END + 0x30,                          // 0x114 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_10_4 = EUnitFields.UNIT_END + 0x31,                          // 0x115 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_11_1 = EUnitFields.UNIT_END + 0x32,                          // 0x116 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_11_2 = EUnitFields.UNIT_END + 0x33,                          // 0x117 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_11_3 = EUnitFields.UNIT_END + 0x34,                          // 0x118 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_11_4 = EUnitFields.UNIT_END + 0x35,                          // 0x119 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_12_1 = EUnitFields.UNIT_END + 0x36,                          // 0x11A - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_12_2 = EUnitFields.UNIT_END + 0x37,                          // 0x11B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_12_3 = EUnitFields.UNIT_END + 0x38,                          // 0x11C - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_12_4 = EUnitFields.UNIT_END + 0x39,                          // 0x11D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_13_1 = EUnitFields.UNIT_END + 0x3A,                          // 0x11E - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_13_2 = EUnitFields.UNIT_END + 0x3B,                          // 0x11F - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_13_3 = EUnitFields.UNIT_END + 0x3C,                          // 0x120 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_13_4 = EUnitFields.UNIT_END + 0x3D,                          // 0x121 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_14_1 = EUnitFields.UNIT_END + 0x3E,                          // 0x122 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_14_2 = EUnitFields.UNIT_END + 0x3F,                          // 0x123 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_14_3 = EUnitFields.UNIT_END + 0x40,                          // 0x124 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_14_4 = EUnitFields.UNIT_END + 0x41,                          // 0x125 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_15_1 = EUnitFields.UNIT_END + 0x42,                          // 0x126 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_15_2 = EUnitFields.UNIT_END + 0x43,                          // 0x127 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_15_3 = EUnitFields.UNIT_END + 0x44,                          // 0x128 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_15_4 = EUnitFields.UNIT_END + 0x45,                          // 0x129 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_16_1 = EUnitFields.UNIT_END + 0x46,                          // 0x12A - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_16_2 = EUnitFields.UNIT_END + 0x47,                          // 0x12B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_16_3 = EUnitFields.UNIT_END + 0x48,                          // 0x12C - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_16_4 = EUnitFields.UNIT_END + 0x49,                          // 0x12D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_17_1 = EUnitFields.UNIT_END + 0x4A,                          // 0x12E - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_17_2 = EUnitFields.UNIT_END + 0x4B,                          // 0x12F - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_17_3 = EUnitFields.UNIT_END + 0x4C,                          // 0x130 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_17_4 = EUnitFields.UNIT_END + 0x4D,                          // 0x131 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_18_1 = EUnitFields.UNIT_END + 0x4E,                          // 0x132 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_18_2 = EUnitFields.UNIT_END + 0x4F,                          // 0x133 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_18_3 = EUnitFields.UNIT_END + 0x50,                          // 0x134 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_18_4 = EUnitFields.UNIT_END + 0x51,                          // 0x135 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_19_1 = EUnitFields.UNIT_END + 0x52,                          // 0x136 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_19_2 = EUnitFields.UNIT_END + 0x53,                          // 0x137 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_19_3 = EUnitFields.UNIT_END + 0x54,                          // 0x138 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_19_4 = EUnitFields.UNIT_END + 0x55,                          // 0x139 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_20_1 = EUnitFields.UNIT_END + 0x56,                          // 0x13A - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_20_2 = EUnitFields.UNIT_END + 0x57,                          // 0x13B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_20_3 = EUnitFields.UNIT_END + 0x58,                          // 0x13C - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_20_4 = EUnitFields.UNIT_END + 0x59,                          // 0x13D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_21_1 = EUnitFields.UNIT_END + 0x5A,                          // 0x13E - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_21_2 = EUnitFields.UNIT_END + 0x5B,                          // 0x13F - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_21_3 = EUnitFields.UNIT_END + 0x5C,                          // 0x140 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_21_4 = EUnitFields.UNIT_END + 0x5D,                          // 0x141 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_22_1 = EUnitFields.UNIT_END + 0x5E,                          // 0x142 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_22_2 = EUnitFields.UNIT_END + 0x5F,                          // 0x143 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_22_3 = EUnitFields.UNIT_END + 0x60,                          // 0x144 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_22_4 = EUnitFields.UNIT_END + 0x61,                          // 0x145 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_23_1 = EUnitFields.UNIT_END + 0x62,                          // 0x146 - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_23_2 = EUnitFields.UNIT_END + 0x63,                          // 0x147 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_23_3 = EUnitFields.UNIT_END + 0x64,                          // 0x148 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_23_4 = EUnitFields.UNIT_END + 0x65,                          // 0x149 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_24_1 = EUnitFields.UNIT_END + 0x66,                          // 0x14A - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_24_2 = EUnitFields.UNIT_END + 0x67,                          // 0x14B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_24_3 = EUnitFields.UNIT_END + 0x68,                          // 0x14C - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_24_4 = EUnitFields.UNIT_END + 0x69,                          // 0x14D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_25_1 = EUnitFields.UNIT_END + 0x6A,                          // 0x14E - Size: 1 - Type: INT - Flags: GROUP_ONLY
    PLAYER_QUEST_LOG_25_2 = EUnitFields.UNIT_END + 0x6B,                          // 0x14F - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_QUEST_LOG_25_3 = EUnitFields.UNIT_END + 0x6C,                          // 0x150 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_QUEST_LOG_25_4 = EUnitFields.UNIT_END + 0x6D,                          // 0x151 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_VISIBLE_ITEM_1_CREATOR = EUnitFields.UNIT_END + 0x6E,                  // 0x152 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_1_0 = EUnitFields.UNIT_END + 0x70,                        // 0x154 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_1_PROPERTIES = EUnitFields.UNIT_END + 0x7C,               // 0x160 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_1_PAD = EUnitFields.UNIT_END + 0x7D,                      // 0x161 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_2_CREATOR = EUnitFields.UNIT_END + 0x7E,                  // 0x162 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_2_0 = EUnitFields.UNIT_END + 0x80,                        // 0x164 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_2_PROPERTIES = EUnitFields.UNIT_END + 0x8C,               // 0x170 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_2_PAD = EUnitFields.UNIT_END + 0x8D,                      // 0x171 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_3_CREATOR = EUnitFields.UNIT_END + 0x8E,                  // 0x172 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_3_0 = EUnitFields.UNIT_END + 0x90,                        // 0x174 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_3_PROPERTIES = EUnitFields.UNIT_END + 0x9C,               // 0x180 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_3_PAD = EUnitFields.UNIT_END + 0x9D,                      // 0x181 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_4_CREATOR = EUnitFields.UNIT_END + 0x9E,                  // 0x182 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_4_0 = EUnitFields.UNIT_END + 0xA0,                        // 0x184 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_4_PROPERTIES = EUnitFields.UNIT_END + 0xAC,               // 0x190 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_4_PAD = EUnitFields.UNIT_END + 0xAD,                      // 0x191 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_5_CREATOR = EUnitFields.UNIT_END + 0xAE,                  // 0x192 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_5_0 = EUnitFields.UNIT_END + 0xB0,                        // 0x194 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_5_PROPERTIES = EUnitFields.UNIT_END + 0xBC,               // 0x1A0 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_5_PAD = EUnitFields.UNIT_END + 0xBD,                      // 0x1A1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_6_CREATOR = EUnitFields.UNIT_END + 0xBE,                  // 0x1A2 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_6_0 = EUnitFields.UNIT_END + 0xC0,                        // 0x1A4 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_6_PROPERTIES = EUnitFields.UNIT_END + 0xCC,               // 0x1B0 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_6_PAD = EUnitFields.UNIT_END + 0xCD,                      // 0x1B1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_7_CREATOR = EUnitFields.UNIT_END + 0xCE,                  // 0x1B2 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_7_0 = EUnitFields.UNIT_END + 0xD0,                        // 0x1B4 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_7_PROPERTIES = EUnitFields.UNIT_END + 0xDC,               // 0x1C0 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_7_PAD = EUnitFields.UNIT_END + 0xDD,                      // 0x1C1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_8_CREATOR = EUnitFields.UNIT_END + 0xDE,                  // 0x1C2 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_8_0 = EUnitFields.UNIT_END + 0xE0,                        // 0x1C4 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_8_PROPERTIES = EUnitFields.UNIT_END + 0xEC,               // 0x1D0 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_8_PAD = EUnitFields.UNIT_END + 0xED,                      // 0x1D1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_9_CREATOR = EUnitFields.UNIT_END + 0xEE,                  // 0x1D2 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_9_0 = EUnitFields.UNIT_END + 0xF0,                        // 0x1D4 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_9_PROPERTIES = EUnitFields.UNIT_END + 0xFC,               // 0x1E0 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_9_PAD = EUnitFields.UNIT_END + 0xFD,                      // 0x1E1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_10_CREATOR = EUnitFields.UNIT_END + 0xFE,                 // 0x1E2 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_10_0 = EUnitFields.UNIT_END + 0x100,                      // 0x1E4 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_10_PROPERTIES = EUnitFields.UNIT_END + 0x10C,             // 0x1F0 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_10_PAD = EUnitFields.UNIT_END + 0x10D,                    // 0x1F1 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_11_CREATOR = EUnitFields.UNIT_END + 0x10E,                // 0x1F2 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_11_0 = EUnitFields.UNIT_END + 0x110,                      // 0x1F4 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_11_PROPERTIES = EUnitFields.UNIT_END + 0x11C,             // 0x200 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_11_PAD = EUnitFields.UNIT_END + 0x11D,                    // 0x201 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_12_CREATOR = EUnitFields.UNIT_END + 0x11E,                // 0x202 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_12_0 = EUnitFields.UNIT_END + 0x120,                      // 0x204 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_12_PROPERTIES = EUnitFields.UNIT_END + 0x12C,             // 0x210 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_12_PAD = EUnitFields.UNIT_END + 0x12D,                    // 0x211 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_13_CREATOR = EUnitFields.UNIT_END + 0x12E,                // 0x212 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_13_0 = EUnitFields.UNIT_END + 0x130,                      // 0x214 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_13_PROPERTIES = EUnitFields.UNIT_END + 0x13C,             // 0x220 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_13_PAD = EUnitFields.UNIT_END + 0x13D,                    // 0x221 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_14_CREATOR = EUnitFields.UNIT_END + 0x13E,                // 0x222 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_14_0 = EUnitFields.UNIT_END + 0x140,                      // 0x224 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_14_PROPERTIES = EUnitFields.UNIT_END + 0x14C,             // 0x230 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_14_PAD = EUnitFields.UNIT_END + 0x14D,                    // 0x231 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_15_CREATOR = EUnitFields.UNIT_END + 0x14E,                // 0x232 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_15_0 = EUnitFields.UNIT_END + 0x150,                      // 0x234 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_15_PROPERTIES = EUnitFields.UNIT_END + 0x15C,             // 0x240 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_15_PAD = EUnitFields.UNIT_END + 0x15D,                    // 0x241 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_16_CREATOR = EUnitFields.UNIT_END + 0x15E,                // 0x242 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_16_0 = EUnitFields.UNIT_END + 0x160,                      // 0x244 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_16_PROPERTIES = EUnitFields.UNIT_END + 0x16C,             // 0x250 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_16_PAD = EUnitFields.UNIT_END + 0x16D,                    // 0x251 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_17_CREATOR = EUnitFields.UNIT_END + 0x16E,                // 0x252 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_17_0 = EUnitFields.UNIT_END + 0x170,                      // 0x254 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_17_PROPERTIES = EUnitFields.UNIT_END + 0x17C,             // 0x260 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_17_PAD = EUnitFields.UNIT_END + 0x17D,                    // 0x261 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_18_CREATOR = EUnitFields.UNIT_END + 0x17E,                // 0x262 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_18_0 = EUnitFields.UNIT_END + 0x180,                      // 0x264 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_18_PROPERTIES = EUnitFields.UNIT_END + 0x18C,             // 0x270 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_18_PAD = EUnitFields.UNIT_END + 0x18D,                    // 0x271 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_19_CREATOR = EUnitFields.UNIT_END + 0x18E,                // 0x272 - Size: 2 - Type: GUID - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_19_0 = EUnitFields.UNIT_END + 0x190,                      // 0x274 - Size: 12 - Type: INT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_19_PROPERTIES = EUnitFields.UNIT_END + 0x19C,             // 0x280 - Size: 1 - Type: TWO_SHORT - Flags: PUBLIC
    PLAYER_VISIBLE_ITEM_19_PAD = EUnitFields.UNIT_END + 0x19D,                    // 0x281 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_CHOSEN_TITLE = EUnitFields.UNIT_END + 0x19E,                           // 0x282 - Size: 1 - Type: INT - Flags: PUBLIC
    PLAYER_FIELD_PAD_0 = EUnitFields.UNIT_END + 0x19F,                            // 0x283 - Size: 1 - Type: INT - Flags: NONE
    PLAYER_FIELD_INV_SLOT_HEAD = EUnitFields.UNIT_END + 0x1A0,                    // 0x284 - Size: 46 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_PACK_SLOT_1 = EUnitFields.UNIT_END + 0x1CE,                      // 0x2B2 - Size: 32 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_BANK_SLOT_1 = EUnitFields.UNIT_END + 0x1EE,                      // 0x2D2 - Size: 56 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_BANKBAG_SLOT_1 = EUnitFields.UNIT_END + 0x226,                   // 0x30A - Size: 14 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_VENDORBUYBACK_SLOT_1 = EUnitFields.UNIT_END + 0x234,             // 0x318 - Size: 24 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_KEYRING_SLOT_1 = EUnitFields.UNIT_END + 0x24C,                   // 0x330 - Size: 64 - Type: GUID - Flags: PRIVATE
    PLAYER_FIELD_VANITYPET_SLOT_1 = EUnitFields.UNIT_END + 0x28C,                 // 0x370 - Size: 36 - Type: GUID - Flags: PRIVATE
    PLAYER_FARSIGHT = EUnitFields.UNIT_END + 0x2B0,                               // 0x394 - Size: 2 - Type: GUID - Flags: PRIVATE
    PLAYER__FIELD_KNOWN_TITLES = EUnitFields.UNIT_END + 0x2B2,                    // 0x396 - Size: 2 - Type: GUID - Flags: PRIVATE
    PLAYER_XP = EUnitFields.UNIT_END + 0x2B4,                                     // 0x398 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_NEXT_LEVEL_XP = EUnitFields.UNIT_END + 0x2B5,                          // 0x399 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_SKILL_INFO_1_1 = EUnitFields.UNIT_END + 0x2B6,                         // 0x39A - Size: 384 - Type: TWO_SHORT - Flags: PRIVATE
    PLAYER_CHARACTER_POINTS1 = EUnitFields.UNIT_END + 0x436,                      // 0x51A - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_CHARACTER_POINTS2 = EUnitFields.UNIT_END + 0x437,                      // 0x51B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_TRACK_CREATURES = EUnitFields.UNIT_END + 0x438,                        // 0x51C - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_TRACK_RESOURCES = EUnitFields.UNIT_END + 0x439,                        // 0x51D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_BLOCK_PERCENTAGE = EUnitFields.UNIT_END + 0x43A,                       // 0x51E - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_DODGE_PERCENTAGE = EUnitFields.UNIT_END + 0x43B,                       // 0x51F - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_PARRY_PERCENTAGE = EUnitFields.UNIT_END + 0x43C,                       // 0x520 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_EXPERTISE = EUnitFields.UNIT_END + 0x43D,                              // 0x521 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_OFFHAND_EXPERTISE = EUnitFields.UNIT_END + 0x43E,                      // 0x522 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_CRIT_PERCENTAGE = EUnitFields.UNIT_END + 0x43F,                        // 0x523 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_RANGED_CRIT_PERCENTAGE = EUnitFields.UNIT_END + 0x440,                 // 0x524 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_OFFHAND_CRIT_PERCENTAGE = EUnitFields.UNIT_END + 0x441,                // 0x525 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_SPELL_CRIT_PERCENTAGE1 = EUnitFields.UNIT_END + 0x442,                 // 0x526 - Size: 7 - Type: FLOAT - Flags: PRIVATE
    PLAYER_SHIELD_BLOCK = EUnitFields.UNIT_END + 0x449,                           // 0x52D - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_EXPLORED_ZONES_1 = EUnitFields.UNIT_END + 0x44A,                       // 0x52E - Size: 64 - Type: BYTES - Flags: PRIVATE
    PLAYER_REST_STATE_EXPERIENCE = EUnitFields.UNIT_END + 0x48A,                  // 0x56E - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_COINAGE = EUnitFields.UNIT_END + 0x48B,                          // 0x56F - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_DAMAGE_DONE_POS = EUnitFields.UNIT_END + 0x48C,              // 0x570 - Size: 7 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_DAMAGE_DONE_NEG = EUnitFields.UNIT_END + 0x493,              // 0x577 - Size: 7 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_DAMAGE_DONE_PCT = EUnitFields.UNIT_END + 0x49A,              // 0x57E - Size: 7 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_HEALING_DONE_POS = EUnitFields.UNIT_END + 0x4A1,             // 0x585 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_TARGET_RESISTANCE = EUnitFields.UNIT_END + 0x4A2,            // 0x586 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_TARGET_PHYSICAL_RESISTANCE = EUnitFields.UNIT_END + 0x4A3,   // 0x587 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_BYTES = EUnitFields.UNIT_END + 0x4A4,                            // 0x588 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_AMMO_ID = EUnitFields.UNIT_END + 0x4A5,                                // 0x589 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_SELF_RES_SPELL = EUnitFields.UNIT_END + 0x4A6,                         // 0x58A - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_PVP_MEDALS = EUnitFields.UNIT_END + 0x4A7,                       // 0x58B - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_BUYBACK_PRICE_1 = EUnitFields.UNIT_END + 0x4A8,                  // 0x58C - Size: 12 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_BUYBACK_TIMESTAMP_1 = EUnitFields.UNIT_END + 0x4B4,              // 0x598 - Size: 12 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_KILLS = EUnitFields.UNIT_END + 0x4C0,                            // 0x5A4 - Size: 1 - Type: TWO_SHORT - Flags: PRIVATE
    PLAYER_FIELD_TODAY_CONTRIBUTION = EUnitFields.UNIT_END + 0x4C1,               // 0x5A5 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_YESTERDAY_CONTRIBUTION = EUnitFields.UNIT_END + 0x4C2,           // 0x5A6 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_LIFETIME_HONORBALE_KILLS = EUnitFields.UNIT_END + 0x4C3,         // 0x5A7 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_BYTES2 = EUnitFields.UNIT_END + 0x4C4,                           // 0x5A8 - Size: 1 - Type: BYTES - Flags: PRIVATE
    PLAYER_FIELD_WATCHED_FACTION_INDEX = EUnitFields.UNIT_END + 0x4C5,            // 0x5A9 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_COMBAT_RATING_1 = EUnitFields.UNIT_END + 0x4C6,                  // 0x5AA - Size: 24 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_ARENA_TEAM_INFO_1_1 = EUnitFields.UNIT_END + 0x4DE,              // 0x5C2 - Size: 18 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_HONOR_CURRENCY = EUnitFields.UNIT_END + 0x4F0,                   // 0x5D4 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_ARENA_CURRENCY = EUnitFields.UNIT_END + 0x4F1,                   // 0x5D5 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_MOD_MANA_REGEN = EUnitFields.UNIT_END + 0x4F2,                   // 0x5D6 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_FIELD_MOD_MANA_REGEN_INTERRUPT = EUnitFields.UNIT_END + 0x4F3,         // 0x5D7 - Size: 1 - Type: FLOAT - Flags: PRIVATE
    PLAYER_FIELD_MAX_LEVEL = EUnitFields.UNIT_END + 0x4F4,                        // 0x5D8 - Size: 1 - Type: INT - Flags: PRIVATE
    PLAYER_FIELD_DAILY_QUESTS_1 = EUnitFields.UNIT_END + 0x4F5,                   // 0x5D9 - Size: 25 - Type: INT - Flags: PRIVATE
    PLAYER_END = EUnitFields.UNIT_END + 0x50E                                     // 0x5F2
}
Public Enum EGameObjectFields
{
    OBJECT_FIELD_CREATED_BY = EObjectFields.OBJECT_END + 0x0,                     // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    GAMEOBJECT_DISPLAYID = EObjectFields.OBJECT_END + 0x2,                        // 0x008 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_FLAGS = EObjectFields.OBJECT_END + 0x3,                            // 0x009 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_ROTATION = EObjectFields.OBJECT_END + 0x4,                         // 0x00A - Size: 4 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_STATE = EObjectFields.OBJECT_END + 0x8,                            // 0x00E - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_POS_X = EObjectFields.OBJECT_END + 0x9,                            // 0x00F - Size: 1 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_POS_Y = EObjectFields.OBJECT_END + 0xA,                            // 0x010 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_POS_Z = EObjectFields.OBJECT_END + 0xB,                            // 0x011 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_FACING = EObjectFields.OBJECT_END + 0xC,                           // 0x012 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    GAMEOBJECT_DYN_FLAGS = EObjectFields.OBJECT_END + 0xD,                        // 0x013 - Size: 1 - Type: INT - Flags: DYNAMIC
    GAMEOBJECT_FACTION = EObjectFields.OBJECT_END + 0xE,                          // 0x014 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_TYPE_ID = EObjectFields.OBJECT_END + 0xF,                          // 0x015 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_LEVEL = EObjectFields.OBJECT_END + 0x10,                           // 0x016 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_ARTKIT = EObjectFields.OBJECT_END + 0x11,                          // 0x017 - Size: 1 - Type: INT - Flags: PUBLIC
    GAMEOBJECT_ANIMPROGRESS = EObjectFields.OBJECT_END + 0x12,                    // 0x018 - Size: 1 - Type: INT - Flags: DYNAMIC
    GAMEOBJECT_PADDING = EObjectFields.OBJECT_END + 0x13,                         // 0x019 - Size: 1 - Type: INT - Flags: NONE
    GAMEOBJECT_END = EObjectFields.OBJECT_END + 0x14                              // 0x01A
}
Public Enum EDynamicObjectFields
{
    DYNAMICOBJECT_CASTER = EObjectFields.OBJECT_END + 0x0,                        // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    DYNAMICOBJECT_BYTES = EObjectFields.OBJECT_END + 0x2,                         // 0x008 - Size: 1 - Type: BYTES - Flags: PUBLIC
    DYNAMICOBJECT_SPELLID = EObjectFields.OBJECT_END + 0x3,                       // 0x009 - Size: 1 - Type: INT - Flags: PUBLIC
    DYNAMICOBJECT_RADIUS = EObjectFields.OBJECT_END + 0x4,                        // 0x00A - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_POS_X = EObjectFields.OBJECT_END + 0x5,                         // 0x00B - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_POS_Y = EObjectFields.OBJECT_END + 0x6,                         // 0x00C - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_POS_Z = EObjectFields.OBJECT_END + 0x7,                         // 0x00D - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_FACING = EObjectFields.OBJECT_END + 0x8,                        // 0x00E - Size: 1 - Type: FLOAT - Flags: PUBLIC
    DYNAMICOBJECT_CASTTIME = EObjectFields.OBJECT_END + 0x9,                      // 0x00F - Size: 1 - Type: INT - Flags: PUBLIC
    DYNAMICOBJECT_END = EObjectFields.OBJECT_END + 0xA                            // 0x010
}
Public Enum ECorpseFields
{
    CORPSE_FIELD_OWNER = EObjectFields.OBJECT_END + 0x0,                          // 0x006 - Size: 2 - Type: GUID - Flags: PUBLIC
    CORPSE_FIELD_FACING = EObjectFields.OBJECT_END + 0x2,                         // 0x008 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    CORPSE_FIELD_POS_X = EObjectFields.OBJECT_END + 0x3,                          // 0x009 - Size: 1 - Type: FLOAT - Flags: PUBLIC
    CORPSE_FIELD_POS_Y = EObjectFields.OBJECT_END + 0x4,                          // 0x00A - Size: 1 - Type: FLOAT - Flags: PUBLIC
    CORPSE_FIELD_POS_Z = EObjectFields.OBJECT_END + 0x5,                          // 0x00B - Size: 1 - Type: FLOAT - Flags: PUBLIC
    CORPSE_FIELD_DISPLAY_ID = EObjectFields.OBJECT_END + 0x6,                     // 0x00C - Size: 1 - Type: INT - Flags: PUBLIC
    CORPSE_FIELD_ITEM = EObjectFields.OBJECT_END + 0x7,                           // 0x00D - Size: 19 - Type: INT - Flags: PUBLIC
    CORPSE_FIELD_BYTES_1 = EObjectFields.OBJECT_END + 0x1A,                       // 0x020 - Size: 1 - Type: BYTES - Flags: PUBLIC
    CORPSE_FIELD_BYTES_2 = EObjectFields.OBJECT_END + 0x1B,                       // 0x021 - Size: 1 - Type: BYTES - Flags: PUBLIC
    CORPSE_FIELD_GUILD = EObjectFields.OBJECT_END + 0x1C,                         // 0x022 - Size: 1 - Type: INT - Flags: PUBLIC
    CORPSE_FIELD_FLAGS = EObjectFields.OBJECT_END + 0x1D,                         // 0x023 - Size: 1 - Type: INT - Flags: PUBLIC
    CORPSE_FIELD_DYNAMIC_FLAGS = EObjectFields.OBJECT_END + 0x1E,                 // 0x024 - Size: 1 - Type: INT - Flags: DYNAMIC
    CORPSE_END = EObjectFields.OBJECT_END + 0x1F                                  // 0x025
}
